import { processVideo, onEngineProgress } from './ffmpeg-engine.js';

const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];

const API_BASE = (document.querySelector('meta[name="bilireels-api"]')?.content || '').replace(/\/$/, '');
const API_URL = API_BASE || '/.netlify/functions/video-api';

const state = {
  source: null,
  file: null,
  objectUrl: null,
  duration: 30,
  quality: '720p',
  smartSplit: true,
  subtitles: true,
  language: 'ar',
  logoUrl: null,
  remote: null,
};

const I18N = {
  ar: { dir:'rtl', lang:'ar', navFeatures:'المميزات', navWorkflow:'كيف يعمل', navStudio:'الاستوديو', theme:'تغيير المظهر', eyebrow:'استوديو الفيديو → Reels', premium:'✦ مساحة صانع محتوى احترافية', heroTitle:'حوّل الفيديو الطويل', heroTitle2:'إلى Reels جاهزة.', heroDesc:'استوديو حديث لمعالجة الفيديو، اختيار الجودة، الترجمة، الـBranding وتقسيم المحتوى إلى أجزاء منظمة — للمحتوى الذي تملك حق استخدامه.', start:'ابدأ الآن', how:'شاهد الطريقة', fast:'⚡ سريع', organized:'◈ منظم', mobile:'▣ Mobile First', source:'المصدر', enterVideo:'أدخل الفيديو', upload:'رفع فيديو', sourceLink:'رابط مصدر', drop:'اسحب الفيديو هنا أو اضغط للاختيار', formats:'MP4 / WEBM / MOV — المعاينة المحلية تعمل بدون رفع للسيرفر', choose:'اختيار فيديو', urlPlaceholder:'ألصق رابط فيديو عام ومصرح باستخدامه…', analyze:'تحليل', urlHint:'الصق رابط فيديو عام من خدمة مدعومة. سيقوم الـBackend بجلب معلومات المصدر ثم توفير الفيديو للمعالجة.', change:'تغيير الفيديو', workspace:'إعدادات المعالجة', output:'صيغة الإخراج', vertical:'عمودي 9:16', quality:'اختيار الجودة', light:'خفيف', balanced:'متوازن', highest:'أعلى', subtitles:'الترجمة', makeSubs:'إنشاء Subtitles', brand:'الشعار', addLogo:'＋ أضف Logo', logoHint:'PNG / JPG / WEBP / SVG', size:'الحجم', opacity:'الشفافية', split:'التقسيم', sec30:'30 ثانية', sec60:'60 ثانية', sec90:'90 ثانية', sec120:'120 ثانية', custom:'مخصص', customSeconds:'المدة بالثواني', smart:'Smart Split', smartDesc:'تقسيم منظم يحاول الحفاظ على حدود المقاطع.', ready:'جاهز للمعالجة', create:'إنشاء Reels', result:'نتيجة المعالجة', downloadAll:'تحميل الكل', featuresTitle:'كل ما تحتاجه في مكان واحد.', local:'Local Preview', localDesc:'شاهد الفيديو الذي اخترته مباشرة قبل بدء المعالجة.', branding:'Smart Branding', brandingDesc:'إضافة شعارك والتحكم بالحجم والشفافية مع Preview حقيقي.', reelEngine:'Reel Engine', reelDesc:'اختيار 30 / 60 / 90 / 120 ثانية أو مدة مخصصة.', batch:'Batch Output', batchDesc:'استقبال Reels منفردة أو ZIP من محرك المعالجة.', flowTitle:'مصدر واحد.<br>إعدادات واضحة.<br><em>نتيجة منظمة.</em>', step1:'ارفع الفيديو أو أدخل المصدر', step2:'اختر الجودة والترجمة', step3:'أضف الـBranding', step4:'اختر التقسيم وأنشئ Reels', toastLoaded:'تم تحميل الفيديو بنجاح.', toastInvalid:'اختر ملف فيديو صالحاً.', toastPaste:'ألصق الرابط أولاً.', toastInvalidUrl:'الرابط غير صالح.', analyzing:'جارِ تحليل الرابط…', remoteReady:'تم جلب المصدر بنجاح.', processing:'جاري المعالجة…', complete:'اكتملت المعالجة.', error:'حدث خطأ أثناء المعالجة.', remoteError:'تعذر جلب الفيديو من الرابط. تأكد أن الرابط عام ومتاح.' },
  en: { dir:'ltr', lang:'en', navFeatures:'Features', navWorkflow:'How it works', navStudio:'Studio', theme:'Change theme', eyebrow:'VIDEO → REELS STUDIO', premium:'✦ PREMIUM CREATOR WORKSPACE', heroTitle:'Turn long videos', heroTitle2:'into ready Reels.', heroDesc:'A modern studio for video processing, quality selection, subtitles, branding and structured splitting — for content you have permission to use.', start:'Start now', how:'See how it works', fast:'⚡ Fast', organized:'◈ Organized', mobile:'▣ Mobile First', source:'SOURCE', enterVideo:'Add your video', upload:'Upload video', sourceLink:'Video URL', drop:'Drop a video here or tap to choose', formats:'MP4 / WEBM / MOV — local preview without uploading to the server', choose:'Choose video', urlPlaceholder:'Paste a public video URL you are authorized to use…', analyze:'Analyze', urlHint:'Paste a public video URL from a supported service. The backend resolves the source and provides it for processing.', change:'Change video', workspace:'Processing settings', output:'OUTPUT FORMAT', vertical:'Vertical 9:16', quality:'QUALITY', light:'Light', balanced:'Balanced', highest:'Highest', subtitles:'SUBTITLES', makeSubs:'Create subtitles', brand:'BRANDING', addLogo:'＋ Add Logo', logoHint:'PNG / JPG / WEBP / SVG', size:'Size', opacity:'Opacity', split:'SPLIT', sec30:'30 sec', sec60:'60 sec', sec90:'90 sec', sec120:'120 sec', custom:'Custom', customSeconds:'Duration in seconds', smart:'Smart Split', smartDesc:'Structured splitting that tries to preserve clip boundaries.', ready:'READY TO PROCESS', create:'Create Reels', result:'Processing result', downloadAll:'Download all', featuresTitle:'Everything you need in one place.', local:'Local Preview', localDesc:'Preview your selected video before processing.', branding:'Smart Branding', brandingDesc:'Add your logo and control size and opacity with a real preview.', reelEngine:'Reel Engine', reelDesc:'Choose 30 / 60 / 90 / 120 seconds or a custom duration.', batch:'Batch Output', batchDesc:'Receive individual Reels or a ZIP from the processing engine.', flowTitle:'One source.<br>Clear settings.<br><em>Organized output.</em>', step1:'Upload a video or add a source', step2:'Choose quality and subtitles', step3:'Add your branding', step4:'Choose splitting and create Reels', toastLoaded:'Video loaded successfully.', toastInvalid:'Choose a valid video file.', toastPaste:'Paste a URL first.', toastInvalidUrl:'Invalid URL.', analyzing:'Analyzing URL…', remoteReady:'Source resolved successfully.', processing:'Processing…', complete:'Processing complete.', error:'An error occurred during processing.', remoteError:'Could not fetch the video from this URL. Make sure it is public and available.' },
  fr: { dir:'ltr', lang:'fr', navFeatures:'Fonctionnalités', navWorkflow:'Fonctionnement', navStudio:'Studio', theme:'Changer le thème', eyebrow:'STUDIO VIDÉO → REELS', premium:'✦ ESPACE CRÉATEUR PREMIUM', heroTitle:'Transformez vos longues vidéos', heroTitle2:'en Reels prêtes.', heroDesc:'Un studio moderne pour traiter les vidéos, choisir la qualité, les sous-titres, le branding et le découpage structuré.', start:'Commencer', how:'Voir le fonctionnement', fast:'⚡ Rapide', organized:'◈ Organisé', mobile:'▣ Mobile First', source:'SOURCE', enterVideo:'Ajouter une vidéo', upload:'Importer une vidéo', sourceLink:'URL vidéo', drop:'Déposez une vidéo ici ou appuyez pour choisir', formats:'MP4 / WEBM / MOV — aperçu local sans envoi au serveur', choose:'Choisir une vidéo', urlPlaceholder:'Collez une URL vidéo publique que vous êtes autorisé à utiliser…', analyze:'Analyser', urlHint:'Collez une URL vidéo publique prise en charge. Le backend résout la source puis la rend disponible pour le traitement.', change:'Changer la vidéo', workspace:'Paramètres de traitement', output:'FORMAT DE SORTIE', vertical:'Vertical 9:16', quality:'QUALITÉ', light:'Léger', balanced:'Équilibré', highest:'Maximum', subtitles:'SOUS-TITRES', makeSubs:'Créer les sous-titres', brand:'BRANDING', addLogo:'＋ Ajouter un logo', logoHint:'PNG / JPG / WEBP / SVG', size:'Taille', opacity:'Opacité', split:'DÉCOUPAGE', sec30:'30 sec', sec60:'60 sec', sec90:'90 sec', sec120:'120 sec', custom:'Personnalisé', customSeconds:'Durée en secondes', smart:'Smart Split', smartDesc:'Découpage structuré en conservant autant que possible les limites des séquences.', ready:'PRÊT', create:'Créer les Reels', result:'Résultat', downloadAll:'Tout télécharger', featuresTitle:'Tout ce dont vous avez besoin au même endroit.', local:'Aperçu local', localDesc:'Prévisualisez votre vidéo avant le traitement.', branding:'Smart Branding', brandingDesc:'Ajoutez votre logo et contrôlez sa taille et son opacité.', reelEngine:'Reel Engine', reelDesc:'Choisissez 30 / 60 / 90 / 120 secondes ou une durée personnalisée.', batch:'Batch Output', batchDesc:'Recevez des Reels séparés ou un ZIP.', flowTitle:'Une source.<br>Des réglages clairs.<br><em>Un résultat organisé.</em>', step1:'Importez la vidéo ou ajoutez une source', step2:'Choisissez qualité et sous-titres', step3:'Ajoutez votre branding', step4:'Choisissez le découpage et créez les Reels', toastLoaded:'Vidéo chargée.', toastInvalid:'Choisissez une vidéo valide.', toastPaste:'Collez d’abord le lien.', toastInvalidUrl:'URL invalide.', analyzing:'Analyse du lien…', remoteReady:'Source récupérée.', processing:'Traitement…', complete:'Traitement terminé.', error:'Erreur pendant le traitement.', remoteError:'Impossible de récupérer cette vidéo. Vérifiez que le lien est public.' },
  es: { dir:'ltr', lang:'es', navFeatures:'Funciones', navWorkflow:'Cómo funciona', navStudio:'Estudio', theme:'Cambiar tema', eyebrow:'ESTUDIO DE VIDEO → REELS', premium:'✦ ESPACIO PREMIUM PARA CREADORES', heroTitle:'Convierte vídeos largos', heroTitle2:'en Reels listos.', heroDesc:'Un estudio moderno para procesar vídeos, elegir calidad, subtítulos, branding y dividir el contenido.', start:'Empezar', how:'Ver cómo funciona', fast:'⚡ Rápido', organized:'◈ Organizado', mobile:'▣ Mobile First', source:'FUENTE', enterVideo:'Añadir vídeo', upload:'Subir vídeo', sourceLink:'URL del vídeo', drop:'Arrastra un vídeo aquí o pulsa para elegir', formats:'MP4 / WEBM / MOV — vista previa local sin subir al servidor', choose:'Elegir vídeo', urlPlaceholder:'Pega una URL pública que tengas permiso para usar…', analyze:'Analizar', urlHint:'Pega una URL pública compatible. El backend resolverá la fuente para procesarla.', change:'Cambiar vídeo', workspace:'Ajustes de procesamiento', output:'FORMATO', vertical:'Vertical 9:16', quality:'CALIDAD', light:'Ligero', balanced:'Equilibrado', highest:'Máximo', subtitles:'SUBTÍTULOS', makeSubs:'Crear subtítulos', brand:'BRANDING', addLogo:'＋ Añadir logo', logoHint:'PNG / JPG / WEBP / SVG', size:'Tamaño', opacity:'Opacidad', split:'DIVISIÓN', sec30:'30 s', sec60:'60 s', sec90:'90 s', sec120:'120 s', custom:'Personalizado', customSeconds:'Duración en segundos', smart:'Smart Split', smartDesc:'División estructurada para conservar los límites de los clips.', ready:'LISTO', create:'Crear Reels', result:'Resultado', downloadAll:'Descargar todo', featuresTitle:'Todo lo que necesitas en un solo lugar.', local:'Vista previa local', localDesc:'Mira el vídeo antes de procesarlo.', branding:'Smart Branding', brandingDesc:'Añade tu logo y controla tamaño y opacidad.', reelEngine:'Reel Engine', reelDesc:'Elige 30 / 60 / 90 / 120 segundos o una duración personalizada.', batch:'Batch Output', batchDesc:'Recibe Reels individuales o un ZIP.', flowTitle:'Una fuente.<br>Ajustes claros.<br><em>Resultado organizado.</em>', step1:'Sube el vídeo o añade una fuente', step2:'Elige calidad y subtítulos', step3:'Añade tu branding', step4:'Elige la división y crea Reels', toastLoaded:'Vídeo cargado.', toastInvalid:'Elige un vídeo válido.', toastPaste:'Pega primero el enlace.', toastInvalidUrl:'URL no válida.', analyzing:'Analizando…', remoteReady:'Fuente obtenida.', processing:'Procesando…', complete:'Procesamiento terminado.', error:'Error durante el procesamiento.', remoteError:'No se pudo obtener el vídeo. Comprueba que sea público.' },
  de: { dir:'ltr', lang:'de', navFeatures:'Funktionen', navWorkflow:'So funktioniert es', navStudio:'Studio', theme:'Design ändern', eyebrow:'VIDEO → REELS STUDIO', premium:'✦ PREMIUM CREATOR WORKSPACE', heroTitle:'Lange Videos in', heroTitle2:'fertige Reels verwandeln.', heroDesc:'Modernes Studio für Videoverarbeitung, Qualität, Untertitel, Branding und strukturiertes Teilen.', start:'Starten', how:'So funktioniert es', fast:'⚡ Schnell', organized:'◈ Organisiert', mobile:'▣ Mobile First', source:'QUELLE', enterVideo:'Video hinzufügen', upload:'Video hochladen', sourceLink:'Video-URL', drop:'Video hier ablegen oder auswählen', formats:'MP4 / WEBM / MOV — lokale Vorschau ohne Upload', choose:'Video auswählen', urlPlaceholder:'Öffentliche Video-URL einfügen…', analyze:'Analysieren', urlHint:'Öffentliche unterstützte Video-URL einfügen. Das Backend löst die Quelle zur Verarbeitung auf.', change:'Video ändern', workspace:'Verarbeitungseinstellungen', output:'AUSGABEFORMAT', vertical:'Vertikal 9:16', quality:'QUALITÄT', light:'Leicht', balanced:'Ausgewogen', highest:'Höchste', subtitles:'UNTERTITEL', makeSubs:'Untertitel erstellen', brand:'BRANDING', addLogo:'＋ Logo hinzufügen', logoHint:'PNG / JPG / WEBP / SVG', size:'Größe', opacity:'Deckkraft', split:'TEILUNG', sec30:'30 Sek.', sec60:'60 Sek.', sec90:'90 Sek.', sec120:'120 Sek.', custom:'Benutzerdefiniert', customSeconds:'Dauer in Sekunden', smart:'Smart Split', smartDesc:'Strukturiertes Teilen mit möglichst natürlichen Clipgrenzen.', ready:'BEREIT', create:'Reels erstellen', result:'Ergebnis', downloadAll:'Alle herunterladen', featuresTitle:'Alles, was du brauchst, an einem Ort.', local:'Lokale Vorschau', localDesc:'Video vor der Verarbeitung ansehen.', branding:'Smart Branding', brandingDesc:'Logo hinzufügen und Größe/Deckkraft steuern.', reelEngine:'Reel Engine', reelDesc:'30 / 60 / 90 / 120 Sekunden oder eigene Dauer.', batch:'Batch Output', batchDesc:'Einzelne Reels oder ZIP erhalten.', flowTitle:'Eine Quelle.<br>Klare Einstellungen.<br><em>Organisiertes Ergebnis.</em>', step1:'Video hochladen oder Quelle hinzufügen', step2:'Qualität und Untertitel wählen', step3:'Branding hinzufügen', step4:'Teilung wählen und Reels erstellen', toastLoaded:'Video geladen.', toastInvalid:'Gültiges Video auswählen.', toastPaste:'Zuerst URL einfügen.', toastInvalidUrl:'Ungültige URL.', analyzing:'URL wird analysiert…', remoteReady:'Quelle erfolgreich geladen.', processing:'Verarbeitung…', complete:'Verarbeitung abgeschlossen.', error:'Fehler bei der Verarbeitung.', remoteError:'Video konnte nicht abgerufen werden. Prüfe, ob es öffentlich ist.' },
  tr: { dir:'ltr', lang:'tr', navFeatures:'Özellikler', navWorkflow:'Nasıl çalışır', navStudio:'Stüdyo', theme:'Temayı değiştir', eyebrow:'VİDEO → REELS STÜDYOSU', premium:'✦ PREMIUM İÇERİK ÜRETİCİ ALANI', heroTitle:'Uzun videoları', heroTitle2:'hazır Reelslere dönüştür.', heroDesc:'Video işleme, kalite seçimi, altyazı, markalama ve düzenli bölme için modern stüdyo.', start:'Başla', how:'Nasıl çalıştığını gör', fast:'⚡ Hızlı', organized:'◈ Düzenli', mobile:'▣ Mobile First', source:'KAYNAK', enterVideo:'Video ekle', upload:'Video yükle', sourceLink:'Video URL', drop:'Videoyu buraya bırak veya seçmek için dokun', formats:'MP4 / WEBM / MOV — sunucuya yüklemeden yerel önizleme', choose:'Video seç', urlPlaceholder:'İzinli olduğunuz herkese açık video URL’sini yapıştırın…', analyze:'Analiz et', urlHint:'Desteklenen herkese açık bir video URL’si girin. Backend kaynağı çözümler.', change:'Videoyu değiştir', workspace:'İşleme ayarları', output:'ÇIKIŞ FORMATI', vertical:'Dikey 9:16', quality:'KALİTE', light:'Hafif', balanced:'Dengeli', highest:'En yüksek', subtitles:'ALTYAZI', makeSubs:'Altyazı oluştur', brand:'MARKALAMA', addLogo:'＋ Logo ekle', logoHint:'PNG / JPG / WEBP / SVG', size:'Boyut', opacity:'Opaklık', split:'BÖLME', sec30:'30 sn', sec60:'60 sn', sec90:'90 sn', sec120:'120 sn', custom:'Özel', customSeconds:'Saniye cinsinden süre', smart:'Smart Split', smartDesc:'Klip sınırlarını korumaya çalışan düzenli bölme.', ready:'HAZIR', create:'Reels oluştur', result:'Sonuç', downloadAll:'Tümünü indir', featuresTitle:'İhtiyacınız olan her şey tek yerde.', local:'Yerel önizleme', localDesc:'İşlemeden önce videoyu izleyin.', branding:'Smart Branding', brandingDesc:'Logo ekleyin ve boyut/opaklığı ayarlayın.', reelEngine:'Reel Engine', reelDesc:'30 / 60 / 90 / 120 saniye veya özel süre seçin.', batch:'Batch Output', batchDesc:'Tek tek Reels veya ZIP alın.', flowTitle:'Tek kaynak.<br>Net ayarlar.<br><em>Düzenli sonuç.</em>', step1:'Video yükle veya kaynak ekle', step2:'Kalite ve altyazıyı seç', step3:'Markalamanı ekle', step4:'Bölmeyi seç ve Reels oluştur', toastLoaded:'Video yüklendi.', toastInvalid:'Geçerli bir video seçin.', toastPaste:'Önce bağlantıyı yapıştırın.', toastInvalidUrl:'Geçersiz URL.', analyzing:'URL analiz ediliyor…', remoteReady:'Kaynak alındı.', processing:'İşleniyor…', complete:'İşlem tamamlandı.', error:'İşleme sırasında hata oluştu.', remoteError:'Video alınamadı. Herkese açık olduğundan emin olun.' },
  zh: { dir:'ltr', lang:'zh', navFeatures:'功能', navWorkflow:'工作流程', navStudio:'工作室', theme:'切换主题', eyebrow:'视频 → Reels 工作室', premium:'✦ 高级创作者工作区', heroTitle:'将长视频', heroTitle2:'转换为 Reels。', heroDesc:'现代视频处理工作室，支持质量、字幕、品牌和结构化分割。', start:'立即开始', how:'查看流程', fast:'⚡ 快速', organized:'◈ 有序', mobile:'▣ 移动优先', source:'来源', enterVideo:'添加视频', upload:'上传视频', sourceLink:'视频链接', drop:'拖入视频或点击选择', formats:'MP4 / WEBM / MOV — 本地预览，不上传服务器', choose:'选择视频', urlPlaceholder:'粘贴你有权使用的公开视频链接…', analyze:'分析', urlHint:'粘贴受支持的公开视频链接，后端会解析并提供处理源。', change:'更换视频', workspace:'处理设置', output:'输出格式', vertical:'竖屏 9:16', quality:'质量', light:'轻量', balanced:'均衡', highest:'最高', subtitles:'字幕', makeSubs:'生成字幕', brand:'品牌', addLogo:'＋ 添加 Logo', logoHint:'PNG / JPG / WEBP / SVG', size:'大小', opacity:'透明度', split:'分割', sec30:'30 秒', sec60:'60 秒', sec90:'90 秒', sec120:'120 秒', custom:'自定义', customSeconds:'秒数', smart:'Smart Split', smartDesc:'尽量保持片段边界的结构化分割。', ready:'准备就绪', create:'创建 Reels', result:'处理结果', downloadAll:'全部下载', featuresTitle:'你需要的一切都在这里。', local:'本地预览', localDesc:'处理前预览所选视频。', branding:'智能品牌', brandingDesc:'添加 Logo 并控制大小和透明度。', reelEngine:'Reel Engine', reelDesc:'选择 30 / 60 / 90 / 120 秒或自定义时长。', batch:'批量输出', batchDesc:'获取单个 Reels 或 ZIP。', flowTitle:'一个来源。<br>清晰设置。<br><em>有序结果。</em>', step1:'上传视频或添加来源', step2:'选择质量和字幕', step3:'添加品牌', step4:'选择分割并创建 Reels', toastLoaded:'视频加载成功。', toastInvalid:'请选择有效视频。', toastPaste:'请先粘贴链接。', toastInvalidUrl:'链接无效。', analyzing:'正在分析链接…', remoteReady:'来源获取成功。', processing:'正在处理…', complete:'处理完成。', error:'处理时发生错误。', remoteError:'无法获取视频，请确认链接公开可用。' },
  ja: { dir:'ltr', lang:'ja', navFeatures:'機能', navWorkflow:'使い方', navStudio:'スタジオ', theme:'テーマ変更', eyebrow:'VIDEO → REELS STUDIO', premium:'✦ PREMIUM CREATOR WORKSPACE', heroTitle:'長い動画を', heroTitle2:'Reelsに変換。', heroDesc:'動画処理、品質、字幕、ブランディング、分割をまとめたモダンなスタジオ。', start:'開始', how:'使い方を見る', fast:'⚡ 高速', organized:'◈ 整理', mobile:'▣ Mobile First', source:'ソース', enterVideo:'動画を追加', upload:'動画をアップロード', sourceLink:'動画URL', drop:'動画をドロップまたは選択', formats:'MP4 / WEBM / MOV — サーバーへ送信せずローカルプレビュー', choose:'動画を選択', urlPlaceholder:'利用権限のある公開動画URLを貼り付け…', analyze:'解析', urlHint:'対応サービスの公開動画URLを貼り付けると、バックエンドが処理用ソースを取得します。', change:'動画を変更', workspace:'処理設定', output:'出力形式', vertical:'縦 9:16', quality:'品質', light:'軽量', balanced:'バランス', highest:'最高', subtitles:'字幕', makeSubs:'字幕を作成', brand:'ブランディング', addLogo:'＋ ロゴを追加', logoHint:'PNG / JPG / WEBP / SVG', size:'サイズ', opacity:'不透明度', split:'分割', sec30:'30秒', sec60:'60秒', sec90:'90秒', sec120:'120秒', custom:'カスタム', customSeconds:'秒数', smart:'Smart Split', smartDesc:'クリップ境界を保ちやすい構造的な分割。', ready:'準備完了', create:'Reelsを作成', result:'処理結果', downloadAll:'すべてダウンロード', featuresTitle:'必要なものをすべて一か所に。', local:'ローカルプレビュー', localDesc:'処理前に動画を確認できます。', branding:'Smart Branding', brandingDesc:'ロゴを追加しサイズと不透明度を調整。', reelEngine:'Reel Engine', reelDesc:'30 / 60 / 90 / 120秒またはカスタム。', batch:'Batch Output', batchDesc:'個別ReelsまたはZIPを取得。', flowTitle:'1つのソース。<br>明確な設定。<br><em>整理された結果。</em>', step1:'動画をアップロードまたはソースを追加', step2:'品質と字幕を選択', step3:'ブランディングを追加', step4:'分割を選びReelsを作成', toastLoaded:'動画を読み込みました。', toastInvalid:'有効な動画を選択してください。', toastPaste:'先にURLを貼り付けてください。', toastInvalidUrl:'URLが無効です。', analyzing:'URLを解析中…', remoteReady:'ソースを取得しました。', processing:'処理中…', complete:'処理が完了しました。', error:'処理中にエラーが発生しました。', remoteError:'動画を取得できません。公開リンクか確認してください。' },
  ko: { dir:'ltr', lang:'ko', navFeatures:'기능', navWorkflow:'사용 방법', navStudio:'스튜디오', theme:'테마 변경', eyebrow:'VIDEO → REELS STUDIO', premium:'✦ PREMIUM CREATOR WORKSPACE', heroTitle:'긴 영상을', heroTitle2:'Reels로 변환하세요.', heroDesc:'영상 처리, 품질, 자막, 브랜딩, 분할을 위한 모던 스튜디오입니다.', start:'시작하기', how:'사용 방법', fast:'⚡ 빠름', organized:'◈ 정리', mobile:'▣ Mobile First', source:'소스', enterVideo:'영상 추가', upload:'영상 업로드', sourceLink:'영상 URL', drop:'영상을 드롭하거나 선택하세요', formats:'MP4 / WEBM / MOV — 서버 업로드 없는 로컬 미리보기', choose:'영상 선택', urlPlaceholder:'사용 권한이 있는 공개 영상 URL을 붙여넣으세요…', analyze:'분석', urlHint:'지원되는 공개 영상 URL을 붙여넣으면 백엔드가 처리용 소스를 가져옵니다.', change:'영상 변경', workspace:'처리 설정', output:'출력 형식', vertical:'세로 9:16', quality:'품질', light:'가벼움', balanced:'균형', highest:'최고', subtitles:'자막', makeSubs:'자막 생성', brand:'브랜딩', addLogo:'＋ 로고 추가', logoHint:'PNG / JPG / WEBP / SVG', size:'크기', opacity:'불투명도', split:'분할', sec30:'30초', sec60:'60초', sec90:'90초', sec120:'120초', custom:'사용자 지정', customSeconds:'초 단위 시간', smart:'Smart Split', smartDesc:'클립 경계를 최대한 유지하는 구조적 분할.', ready:'준비 완료', create:'Reels 만들기', result:'처리 결과', downloadAll:'전체 다운로드', featuresTitle:'필요한 모든 것을 한 곳에서.', local:'로컬 미리보기', localDesc:'처리 전에 선택한 영상을 확인하세요.', branding:'Smart Branding', brandingDesc:'로고를 추가하고 크기와 불투명도를 조정하세요.', reelEngine:'Reel Engine', reelDesc:'30 / 60 / 90 / 120초 또는 사용자 지정.', batch:'Batch Output', batchDesc:'개별 Reels 또는 ZIP으로 받습니다.', flowTitle:'하나의 소스.<br>명확한 설정.<br><em>정리된 결과.</em>', step1:'영상을 업로드하거나 소스 추가', step2:'품질과 자막 선택', step3:'브랜딩 추가', step4:'분할을 선택하고 Reels 생성', toastLoaded:'영상이 로드되었습니다.', toastInvalid:'유효한 영상을 선택하세요.', toastPaste:'먼저 링크를 붙여넣으세요.', toastInvalidUrl:'잘못된 URL입니다.', analyzing:'URL 분석 중…', remoteReady:'소스를 가져왔습니다.', processing:'처리 중…', complete:'처리가 완료되었습니다.', error:'처리 중 오류가 발생했습니다.', remoteError:'영상을 가져오지 못했습니다. 공개 링크인지 확인하세요.' }
};

function detectLanguage() {
  const saved = localStorage.getItem('bilireels-language');
  if (saved && I18N[saved]) return saved;
  const candidates = [...(navigator.languages || []), navigator.language || 'en'].map(x => x.toLowerCase());
  for (const c of candidates) {
    const base = c.split('-')[0];
    if (I18N[base]) return base;
  }
  return 'en';
}

function addLanguageControl() {
  const nav = document.querySelector('.nav nav');
  if (!nav || document.querySelector('#siteLanguage')) return;
  const wrap = document.createElement('label');
  wrap.className = 'language-switcher';
  wrap.innerHTML = `<span aria-hidden="true">🌐</span><select id="siteLanguage" aria-label="Language"></select>`;
  nav.appendChild(wrap);
  const select = wrap.querySelector('select');
  const names = { ar:'العربية', en:'English', fr:'Français', es:'Español', de:'Deutsch', tr:'Türkçe', zh:'中文', ja:'日本語', ko:'한국어' };
  Object.keys(I18N).forEach(k => { const o=document.createElement('option'); o.value=k; o.textContent=names[k] || k; select.appendChild(o); });
  select.value = detectLanguage();
  select.addEventListener('change', () => setLanguage(select.value));
}

function translateElement(el, key) {
  const t = I18N[state.language]?.[key];
  if (t == null) return;
  if (t.includes('<br>') || t.includes('<em>')) el.innerHTML = t; else el.textContent = t;
}

function setLanguage(lang) {
  state.language = I18N[lang] ? lang : 'en';
  localStorage.setItem('bilireels-language', state.language);
  const t = I18N[state.language];
  document.documentElement.lang = t.lang;
  document.documentElement.dir = t.dir;
  document.body.classList.toggle('lang-rtl', t.dir === 'rtl');
  const el = $('#siteLanguage'); if (el) el.value = state.language;
  const map = {
    '.nav nav a:nth-child(1)':'navFeatures','.nav nav a:nth-child(2)':'navWorkflow','.nav nav a:nth-child(3)':'navStudio',
    '#themeBtn':'theme','.eyebrow':'eyebrow','.hero-copy h1':'heroTitle','.hero-copy h1 em':'heroTitle2','.hero-copy p':'heroDesc',
    '.hero-actions .primary':'start','.hero-actions .secondary':'how','.trust span:nth-child(1)':'fast','.trust span:nth-child(2)':'organized','.trust span:nth-child(3)':'mobile',
    '#uploadSource strong':'drop','#uploadSource span':'formats','#uploadSource b':'choose','#urlSource input':'urlPlaceholder','#analyzeForm button':'analyze','#urlSource .hint':'urlHint',
    '#changeVideo':'change','.workspace .section-head h2':'workspace','#subtitleToggle + i':'',
    '#processBtn':'create','#result .section-head h2':'result','#downloadAll':'downloadAll',
    '#features h2':'featuresTitle','.workflow h2':'flowTitle'
  };
  Object.entries(map).forEach(([sel,key]) => { if(key) { const e=$(sel); if(e) translateElement(e,key); }});
  const tabs=$$('.source-tab'); if(tabs[0]) translateElement(tabs[0],'upload'); if(tabs[1]) translateElement(tabs[1],'sourceLink');
  const panels=$$('.panel');
  if(panels[0]) { const e=panels[0].querySelector('.panel-title span:last-child'); if(e) translateElement(e,'output'); const c=panels[0].querySelector('.format-card span'); if(c) translateElement(c,'vertical'); }
  if(panels[1]) { const e=panels[1].querySelector('.panel-title span:last-child'); if(e) translateElement(e,'quality'); }
  if(panels[2]) { const e=panels[2].querySelector('.panel-title span:last-child'); if(e) translateElement(e,'subtitles'); const l=panels[2].querySelector('.switch-line span'); if(l) translateElement(l,'makeSubs'); }
  if(panels[3]) { const e=panels[3].querySelector('.panel-title span:last-child'); if(e) translateElement(e,'brand'); const l=panels[3].querySelector('#logoLabel'); if(l && !state.logoUrl) translateElement(l,'addLogo'); }
  if(panels[4]) { const e=panels[4].querySelector('.panel-title span:last-child'); if(e) translateElement(e,'split'); }
  const q=$$('.options .option'); ['light','balanced','highest'].forEach((k,i)=>q[i] && translateElement(q[i].querySelector('small'),k));
  const split=$$('.split-options .option'); ['sec30','sec60','sec90','sec120','custom'].forEach((k,i)=>split[i] && translateElement(split[i],k));
  const smart=$('#smartSplit')?.closest('.smart-row'); if(smart){ const b=smart.querySelector('b'); const s=smart.querySelector('small'); if(b) translateElement(b,'smart'); if(s) translateElement(s,'smartDesc'); }
  const stepEls=$$('.steps p'); ['step1','step2','step3','step4'].forEach((k,i)=>stepEls[i]&&translateElement(stepEls[i],k));
  const featureEls=$$('.feature-grid article'); [['local','localDesc'],['branding','brandingDesc'],['reelEngine','reelDesc'],['batch','batchDesc']].forEach((pair,i)=>{const a=featureEls[i];if(a){translateElement(a.querySelector('h3'),pair[0]);translateElement(a.querySelector('p'),pair[1]);}});
  const logoLabels=$$('.logo-controls label'); if(logoLabels[0]) translateElement(logoLabels[0].firstChild,'size'); if(logoLabels[1]) translateElement(logoLabels[1].firstChild,'opacity');
}

const toast = (message) => { const el=$('#toast'); if(!el) return; el.textContent=message; el.classList.add('show'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>el.classList.remove('show'),2600); };
const formatBytes = (bytes) => { if(!bytes) return '0 B'; const u=['B','KB','MB','GB']; const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),u.length-1); return `${(bytes/1024**i).toFixed(i?1:0)} ${u[i]}`; };
const formatTime = (seconds) => { if(!Number.isFinite(seconds)) return '—'; const s=Math.round(seconds),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60; return h?`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`:`${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`; };

function updateSummary(){ $('#processSummary').textContent=`${state.file?'1':'1'} · ${state.duration}s · ${state.quality} · 9:16`; }
function showWorkspace(){ $('#workspace').classList.remove('hidden'); $('#workspace').scrollIntoView({behavior:'smooth',block:'start'}); updateSummary(); }

function loadVideo(file){
  if(!file || (!file.type.startsWith('video/') && !/\.(mp4|webm|mov|m4v|mkv)$/i.test(file.name))) return toast(I18N[state.language].toastInvalid);
  if(state.objectUrl) URL.revokeObjectURL(state.objectUrl);
  state.file=file; state.remote=null; state.source='upload'; state.objectUrl=URL.createObjectURL(file);
  const video=$('#videoPreview'); video.onerror=()=>toast(I18N[state.language].toastInvalid); video.src=state.objectUrl; video.load();
  $('#fileName').textContent=file.name; $('#fileSize').textContent=formatBytes(file.size); $('#localPreview').classList.remove('hidden');
  $('#sourceStatus').textContent='● LOADED'; $('#sourceStatus').className='status ready'; $('#logoOverlay').classList.add('hidden');
  video.onloadedmetadata=()=>{ $('#fileDuration').textContent=formatTime(video.duration); toast(I18N[state.language].toastLoaded); showWorkspace(); };
}

async function resolveRemote(url){
  const response=await fetch(`${API_URL}?url=${encodeURIComponent(url)}`,{headers:{Accept:'application/json'}});
  let data={}; try{data=await response.json();}catch{}
  if(!response.ok || !data.ok) throw new Error(data.error || I18N[state.language].remoteError);
  return data;
}

async function loadRemote(data){
  state.source='remote'; state.file=null; state.remote=data;
  $('#sourceStatus').textContent='● READY'; $('#sourceStatus').className='status ready';
  $('#fileName').textContent=data.title || data.filename || 'Remote video'; $('#fileSize').textContent=data.size ? formatBytes(data.size) : 'REMOTE'; $('#fileDuration').textContent=formatTime(data.duration);
  $('#localPreview').classList.remove('hidden');
  const video=$('#videoPreview'); video.src=data.streamUrl; video.load();
  video.onerror=()=>toast(I18N[state.language].remoteError);
  video.onloadedmetadata=()=>{ if(Number.isFinite(video.duration)) $('#fileDuration').textContent=formatTime(video.duration); };
  toast(I18N[state.language].remoteReady); showWorkspace();
}

function wire(){
  state.language=detectLanguage(); addLanguageControl(); setLanguage(state.language);
  $('#videoInput').addEventListener('change',e=>{loadVideo(e.target.files?.[0]); e.target.value='';});
  const dropzone=$('#dropzone');
  ['dragenter','dragover'].forEach(type=>dropzone.addEventListener(type,e=>{e.preventDefault();dropzone.classList.add('dragover');}));
  ['dragleave','drop'].forEach(type=>dropzone.addEventListener(type,e=>{e.preventDefault();dropzone.classList.remove('dragover');}));
  dropzone.addEventListener('drop',e=>loadVideo(e.dataTransfer.files?.[0]));
  $('#changeVideo').addEventListener('click',()=>$('#videoInput').click());
  $$('.source-tab').forEach(tab=>tab.addEventListener('click',()=>{$$('.source-tab').forEach(x=>x.classList.remove('active'));$$('.source-view').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(`#${tab.dataset.source==='upload'?'uploadSource':'urlSource'}`).classList.add('active');}));
  $('#analyzeForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('#videoUrl'),url=input.value.trim();if(!url)return toast(I18N[state.language].toastPaste);try{new URL(url)}catch{return toast(I18N[state.language].toastInvalidUrl)}const btn=e.submitter||$('#analyzeForm button');btn.disabled=true;btn.textContent=I18N[state.language].analyzing;$('#sourceStatus').textContent='● FETCHING';$('#sourceStatus').className='status busy';try{const data=await resolveRemote(url);await loadRemote(data);}catch(err){console.error(err);$('#sourceStatus').textContent='× ERROR';$('#sourceStatus').className='status error';toast(err.message||I18N[state.language].remoteError);}finally{btn.disabled=false;btn.textContent=I18N[state.language].analyze;}});
  $$('.options').forEach(group=>group.addEventListener('click',e=>{const btn=e.target.closest('.option');if(!btn)return;group.querySelectorAll('.option').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(group.dataset.group==='quality')state.quality=btn.dataset.value;updateSummary();}));
  $$('.split-options').forEach(group=>group.addEventListener('click',e=>{const btn=e.target.closest('.option');if(!btn)return;group.querySelectorAll('.option').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const custom=btn.dataset.value==='custom';$('#customDurationWrap').classList.toggle('hidden',!custom);state.duration=custom?Number($('#customDuration').value)||45:Number(btn.dataset.value);updateSummary();}));
  $('#customDuration').addEventListener('input',e=>{state.duration=Math.max(10,Math.min(600,Number(e.target.value)||10));updateSummary();});
  $('#subtitleToggle').addEventListener('change',e=>{state.subtitles=e.target.checked;$('#subtitleOverlay').classList.toggle('hidden',!state.subtitles);updateSummary();});
  $('#language').addEventListener('change',e=>{state.subtitleLanguage=e.target.value;toast(e.target.options[e.target.selectedIndex].text);});
  $('#smartSplit').addEventListener('change',e=>{state.smartSplit=e.target.checked;});
  $('#logoInput').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(state.logoUrl)URL.revokeObjectURL(state.logoUrl);state.logoUrl=URL.createObjectURL(file);$('#logoOverlay').src=state.logoUrl;$('#logoOverlay').classList.remove('hidden');$('#logoLabel').textContent=`✓ ${file.name}`;});
  function updateLogo(){const size=Number($('#logoSize').value),opacity=Number($('#logoOpacity').value);$('#logoSizeValue').textContent=`${size}%`;$('#logoOpacityValue').textContent=`${opacity}%`;$('#logoOverlay').style.width=`${Math.max(42,size*1.8)}px`;$('#logoOverlay').style.opacity=opacity/100;}
  $('#logoSize').addEventListener('input',updateLogo);$('#logoOpacity').addEventListener('input',updateLogo);updateLogo();
  const activeDownloads=[];
  function renderReels(reels){const list=$('#reelsList');list.innerHTML='';activeDownloads.length=0;reels.forEach(reel=>{const item=document.createElement('article');item.className='reel';item.innerHTML=`<div><strong>${reel.filename}</strong><small>9:16 · ${Math.round(reel.duration)}s · ${reel.quality} · ${reel.width}×${reel.height}</small></div><div class="reel-actions"><a class="secondary small" href="${reel.url}" download="${reel.filename}">تحميل</a><a class="secondary small" href="${reel.url}" target="_blank" rel="noopener">معاينة</a></div>`;list.appendChild(item);activeDownloads.push(reel);});}
  onEngineProgress(({progress})=>{const p=Math.round(Math.max(0,Math.min(1,progress))*100);$('#progressBar').style.width=`${p}%`;$('#progressText').textContent=`${p}%`;});
  $('#processBtn').addEventListener('click',async()=>{
    if(!state.file && !state.remote) return toast(I18N[state.language].remoteError);
    const result=$('#result'),button=$('#processBtn');result.classList.remove('hidden');result.scrollIntoView({behavior:'smooth',block:'start'});$('#progressBar').style.width='0%';$('#progressText').textContent='0%';$('#reelsList').innerHTML='';$('#resultStatus').textContent='● PROCESSING';$('#resultStatus').className='status busy';$('#resultNote').textContent=I18N[state.language].processing;button.disabled=true;button.classList.add('processing');
    try{
      let file=state.file;
      if(!file && state.remote){ const r=await fetch(state.remote.streamUrl,{mode:'cors'}); if(!r.ok) throw new Error(I18N[state.language].remoteError); const blob=await r.blob(); file=new File([blob],state.remote.filename||'remote-video.mp4',{type:blob.type||'video/mp4'}); }
      const output=await processVideo({file,duration:state.duration,quality:state.quality,smartSplit:state.smartSplit,onStatus:({message})=>{if(message)$('#resultNote').textContent=message;}});
      renderReels(output.reels);$('#resultStatus').textContent='✓ COMPLETE';$('#resultStatus').className='status ready';$('#resultNote').textContent=`${I18N[state.language].complete} ${output.reels.length} MP4`;toast(I18N[state.language].complete);
    }catch(error){console.error(error);$('#resultStatus').textContent='× ERROR';$('#resultStatus').className='status error';$('#resultNote').textContent=error?.message||I18N[state.language].error;toast(I18N[state.language].error);}finally{button.disabled=false;button.classList.remove('processing');}
  });
  $('#downloadAll').addEventListener('click',()=>{const links=[...document.querySelectorAll('#reelsList a[download]')];if(!links.length)return toast(I18N[state.language].error);links.forEach((a,i)=>setTimeout(()=>a.click(),i*180));});
  $('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('bilireels-theme',document.body.classList.contains('light')?'light':'dark');});
  if(localStorage.getItem('bilireels-theme')==='light')document.body.classList.add('light');
}

document.addEventListener('DOMContentLoaded', wire);
